language: node_js
node_js:
  - "7"
before_install:
  - sudo apt-get update
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get install imagemagick
  - npm install
  - /usr/bin/sqlite3 testDb < ./local/dq.schema
script:
  - npm run test
