version: "3.2"

services:
  upload-microservice:
    image: upload-microservice:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NPM_INSTALL_ARGS=install --production
    ports:
      - "3035:3035"
    volumes:
      - "sources:/usr/src/app/src"
      - "tests:/usr/src/app/test"
      - "config:/usr/src/app/config"
      - "local_data:/usr/src/app/local"

volumes:
  local_data:
  config:
  tests:
  sources:
