version: "3.2"

services:
  upload-microservice:
    image: upload-microservice:dev
    environment:
      - DEBUG=app*
      - JWT_SECRET=thatsmysecret
    volumes:
      - "./src:/usr/src/app/src"
      - "./test:/usr/src/app/test"
      - "./config:/usr/src/app/config"
      - "./local:/usr/src/app/local"
